# -*- coding: utf-8 -*-
"""checkIfPrerequisite

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19590nUeYrPa7so5J0zjWB7OKAA9eMkyU
"""

class Solution(object):
    def checkIfPrerequisite(self, numCourses, prerequisites, queries):
        # Initialize a reachability matrix
        reachable = [[False] * numCourses for _ in range(numCourses)]

        # Mark direct prerequisites
        for u, v in prerequisites:
            reachable[u][v] = True

        # Floyd-Warshall to compute transitive closure
        for k in range(numCourses):
            for i in range(numCourses):
                for j in range(numCourses):
                    reachable[i][j] = reachable[i][j] or (reachable[i][k] and reachable[k][j])

        # Answer each query
        result = []
        for u, v in queries:
            result.append(reachable[u][v])

        return result

s = "abaacbcbb"