# -*- coding: utf-8 -*-
"""constructFromPrePost

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19590nUeYrPa7so5J0zjWB7OKAA9eMkyU
"""

class Solution(object):
    def constructFromPrePost(self, preorder, postorder):
        if not preorder:
            return None

        root = TreeNode(preorder[0])
        if len(preorder) == 1:
            return root

        left_root_idx = postorder.index(preorder[1])
        root.left = self.constructFromPrePost(preorder[1:left_root_idx+2], postorder[:left_root_idx+1])
        root.right = self.constructFromPrePost(preorder[left_root_idx+2:], postorder[left_root_idx+1:-1])

        return root

