# -*- coding: utf-8 -*-
"""getProduct

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19590nUeYrPa7so5J0zjWB7OKAA9eMkyU
"""

class ProductOfNumbers:
    def __init__(self):
        self.prefix_products = [1]

    def add(self, num):
        if num == 0:
            self.prefix_products = [1]
        else:
            self.prefix_products.append(self.prefix_products[-1] * num)

    def getProduct(self, k):
        if k >= len(self.prefix_products):
            return 0
        return self.prefix_products[-1] // self.prefix_products[-(k + 1)]

# Example usage:
productOfNumbers = ProductOfNumbers()
productOfNumbers.add(3)
productOfNumbers.add(0)
productOfNumbers.add(2)
productOfNumbers.add(5)
productOfNumbers.add(4)
print(productOfNumbers.getProduct(2))  # Output: 20
print(productOfNumbers.getProduct(3))  # Output: 40
print(productOfNumbers.getProduct(4))  # Output: 0
productOfNumbers.add(8)
print(productOfNumbers.getProduct(2))  # Output: 32

