# -*- coding: utf-8 -*-
"""numTilePossibilities

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19590nUeYrPa7so5J0zjWB7OKAA9eMkyU
"""

from collections import Counter

class Solution:
    def numTilePossibilities(self, tiles: str) -> int:
        def backtrack(counter):
            total = 0
            for char in counter:
                if counter[char] > 0:
                    counter[char] -= 1
                    total += 1 + backtrack(counter)
                    counter[char] += 1
            return total

        return backtrack(Counter(tiles))

