# -*- coding: utf-8 -*-
"""addSpaces

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19590nUeYrPa7so5J0zjWB7OKAA9eMkyU
"""

class Solution(object):
    def addSpaces(self, s, spaces):

        result = []
        prev = 0
        for space in spaces:
            result.append(s[prev:space])
            prev = space
        result.append(s[prev:])
        return " ".join(result)