# -*- coding: utf-8 -*-
"""countBadPairs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19590nUeYrPa7so5J0zjWB7OKAA9eMkyU
"""

from collections import defaultdict

class Solution:
    def countBadPairs(self, nums):
        freq = defaultdict(int)
        good_pairs = 0
        n = len(nums)

        for i, num in enumerate(nums):
            key = num - i
            good_pairs += freq[key]  # Count pairs with the same key
            freq[key] += 1  # Update frequency

        total_pairs = n * (n - 1) // 2
        return total_pairs - good_pairs  # Bad pairs = total - good

