# -*- coding: utf-8 -*-
"""findDifferentBinaryString

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19590nUeYrPa7so5J0zjWB7OKAA9eMkyU
"""

class Solution(object):
    def findDifferentBinaryString(self, nums):
        n = len(nums)
        num_set = set(nums)
        for i in range(2 ** n):
            binary_str = bin(i)[2:].zfill(n)
            if binary_str not in num_set:
                return binary_str

