# -*- coding: utf-8 -*-
"""maxAscendingSum

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19590nUeYrPa7so5J0zjWB7OKAA9eMkyU
"""

class Solution(object):
    def maxAscendingSum(self, nums):
        max_sum = curr_sum = nums[0]  # Initialize max_sum and curr_sum with the first element

        for i in range(1, len(nums)):
            if nums[i] > nums[i - 1]:  # Continue ascending sequence
                curr_sum += nums[i]
            else:  # Reset if sequence is broken
                curr_sum = nums[i]

            max_sum = max(max_sum, curr_sum)  # Update max_sum

        return max_sum

# Example Test Cases

class Solution(object):
    def maxAscendingSum(self, nums):
        max_sum = curr_sum = nums[0]  # Initialize max_sum and curr_sum with the first element

        for i in range(1, len(nums)):
            if nums[i] > nums[i - 1]:  # Continue ascending sequence
                curr_sum += nums[i]
            else:  # Reset if sequence is broken
                curr_sum = nums[i]

            max_sum = max(max_sum, curr_sum)  # Update max_sum

        return max_sum

# Example Test Cases