# -*- coding: utf-8 -*-
"""minimumLength

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19590nUeYrPa7so5J0zjWB7OKAA9eMkyU
"""

class Solution:
    def minimumLength(self, s: str) -> int:
        left, right = 0, len(s) - 1

        while left < right and s[left] == s[right]:
            char = s[left]

            while left <= right and s[left] == char:
                left += 1

            while left <= right and s[right] == char:
                right -= 1

        return right - left + 1

