# -*- coding: utf-8 -*-
"""minOperations

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19590nUeYrPa7so5J0zjWB7OKAA9eMkyU
"""

import heapq

class Solution:
    @staticmethod
    def minOperations(nums, k):
        heapq.heapify(nums)
        operations = 0

        while nums[0] < k:
            x = heapq.heappop(nums)
            y = heapq.heappop(nums)
            new_val = min(x, y) * 2 + max(x, y)
            heapq.heappush(nums, new_val)
            operations += 1

        return operations

# Example test cases
print(Solution.minOperations([2, 11, 10, 1, 3], 10))  # Output: 2
print(Solution.minOperations([1, 1, 2, 4, 9], 20))   # Output: 4

