# -*- coding: utf-8 -*-
"""numberOfAlternatingGroups

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19590nUeYrPa7so5J0zjWB7OKAA9eMkyU
"""

class Solution(object):
    def numberOfAlternatingGroups(self, colors, k):
        n = len(colors)
        colors += colors[:k-1]
        count = 0

        for i in range(n):
            if all(colors[j] != colors[j+1] for j in range(i, i+k-1)):
                count += 1

        return count

