# -*- coding: utf-8 -*-
"""pivotArray

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19590nUeYrPa7so5J0zjWB7OKAA9eMkyU
"""

class Solution:
    def pivotArray(self, nums, pivot):
        less, equal, greater = [], [], []

        for num in nums:
            if num < pivot:
                less.append(num)
            elif num > pivot:
                greater.append(num)
            else:
                equal.append(num)

        return less + equal + greater

