# -*- coding: utf-8 -*-
"""punishmentNumber

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19590nUeYrPa7so5J0zjWB7OKAA9eMkyU
"""

class Solution:
    def punishmentNumber(self, n):
        def canPartition(num, target, start):
            if start == len(num):
                return target == 0
            for end in range(start + 1, len(num) + 1):
                if canPartition(num, target - int(num[start:end]), end):
                    return True
            return False

        punishment_sum = 0
        for i in range(1, n + 1):
            square_str = str(i * i)
            if canPartition(square_str, i, 0):
                punishment_sum += i * i

        return punishment_sum

