# -*- coding: utf-8 -*-
"""queryResults

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19590nUeYrPa7so5J0zjWB7OKAA9eMkyU
"""

from collections import deque

class Solution(object):
    def queryResults(self, limit, queries):
        ball_colors = {}
        distinct_colors = set()
        result = []

        for x, y in queries:
            if x in ball_colors:
                prev_color = ball_colors[x]
                if prev_color != y and prev_color in distinct_colors:
                    if list(ball_colors.values()).count(prev_color) == 1:
                        distinct_colors.discard(prev_color)
            ball_colors[x] = y
            distinct_colors.add(y)
            result.append(len(distinct_colors))

        return result

    def clearDigits(self, s):
        stack = []
        for char in s:
            if char.isdigit():
                if stack:
                    stack.pop()
            else:
                stack.append(char)
        return "".join(stack)

