# -*- coding: utf-8 -*-
"""removeOccurrences

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19590nUeYrPa7so5J0zjWB7OKAA9eMkyU
"""

class Solution:
    @staticmethod
    def removeOccurrences(s, part):
        while part in s:
            s = s.replace(part, "", 1)
        return s

print(Solution.removeOccurrences("daabcbaabcbc", "abc"))  # Output: "dab"
print(Solution.removeOccurrences("axxxxyyyyb", "xy"))  # Output: "ab"

